### ISSUE TITLE
Low quality window rendering

### ISSUE THREAD

**Issue by delef** [koddr/yandex-music-desktop#1]
Thanks for your work! Is it possible to fix it somehow?

<img width="839" alt="Screenshot 2019-12-28 at 15 24 05" src="https://user-images.githubusercontent.com/2103263/71543641-61b79880-2986-11ea-8010-a6c0b12a1afb.png">

**Comment by delef** [comment]
Pay attention to the font in Safari (on the top) and in the Yandex Music Desktop.

**Comment by koddr** [comment]
@delef I try to solve it, asap :(

Strange thing, I agree.

**Comment by koddr** [comment]
It serious trouble at this moment, because [webview](https://github.com/zserge/webview) module use [Cocoa/WebKit](https://developer.apple.com/documentation/webkit/webview) on macOS for create window, who's `deprecated` by Apple 😞 

Maybe, next version — [webview-x](https://github.com/zserge/webview/tree/webview-x) — solve this, but project is stuck right now... and not guarantee, because webview will use [exactly](https://github.com/zserge/webview/blob/b49a004242bc8b1ffc0182ec8d6412e2ceda10a4/script/build.sh#L8) WebKit framework as I see.

P.S. I tested Windows 10 version on PC and it's looking good..

**Comment by DimaMinka** [comment]
first screen of app, the second one from safari
<img width="1920" alt="Screen Shot 2020-03-29 at 12 34 40" src="https://user-images.githubusercontent.com/12497991/77845818-6b85ad80-71ba-11ea-9602-041c2957d5af.png">
<img width="1920" alt="Screen Shot 2020-03-29 at 12 34 48" src="https://user-images.githubusercontent.com/12497991/77845823-717b8e80-71ba-11ea-967e-f14fa144d25d.png">
same problem with font rendering... if u have any news, tell us...
using on retina displays very hard for the eyes... 
but on external screen (dell 34 UW) font rendered like a charm...

**Comment by Grawl** [comment]
Just faced the same issue on macOS
