### ISSUE TITLE
It doesnt work anymore

### ISSUE THREAD

**Issue by TheRadioGuy** [koddr/yandex-music-desktop#2]
![image](https://user-images.githubusercontent.com/23637939/72631034-b2f2f080-3964-11ea-93e8-ef75ff9b5014.png)
"Your browser is too old, that's why Music can't work"

**Comment by koddr** [comment]
@DuckerMan hi!

What's version of your Windows?

> Tip: try to update your browser as this app tell you and restart Yandex.Music app 😉

**Comment by TheRadioGuy** [comment]
It's Windows 10. I use Google Chrome last versions, so I can't update it

**Comment by koddr** [comment]
@DuckerMan ah, okay. 

Windows 10 shipping with two web browsers: Microsoft Edge and Internet Explorer 11. Do you have Microsoft Edge browser on your Windows 10 system? 

Because Yandex.Music Desktop app running from default OS webview layer, if you removed Edge — webview layer is Internet Explorer 11 (not Google Chrome, because it's third-party software for Windows!).

> And, I thought, web site Yandex.Music not working in Internet Explorer 11 without Flash player (see [this](https://yandex.ru/support/music/troubleshooting/player.html?lang=en)), who not installed by default with system.

I check it from my test-stand with Windows 10 Pro x64 (version 1903, OS build 18362.535):

![Capture](https://user-images.githubusercontent.com/11155743/72662503-16c6f900-39f9-11ea-8cb3-6afdcec383df.PNG)

_On screen (from left to right): Yandex.Music Desktop app, Internet Explorer 11, MS Edge 18._

**Comment by TheRadioGuy** [comment]
Yeah, I dont have Flash Player, So I'm gonna install it and then write here.
